### ISSUE TITLE
API Specs for Tree Inventory

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treeinventory#9]
For On Site Method, we need to have something to ensure requests are coming through the App. @jmiridis 
Forks, and other applications will need approval and `key`, before they can use  On-Site Methods.

- [x] in https://github.com/Plant-for-the-Planet-org/treeinventory/issues/8

**Comment by jmiridis** [comment]
Draft for general specifications to derive API from

### TreeInventory

- PlantContribution
  - new fields
    - location ID (loc_sK8wDLyz6AJR30WuqdA2wR7X7nlM)
    - species now contains multiple records (must be able to handle both)
	- initialGeometry stores a copy of 'geometry' when entity is created
	- captureMode (onsite/offsite)
	- designationType (donated trees, ...?)
- ContributionImage
  - new fields
    - coordinateId
	- coordinateIndex

- PlantRegistrationType (data_class: PlantContribution)
  - plantDate
  - captureMode
  - plantProject
  - designationType
  - species (requires Transformer)
  - geometry
  - contributionImages (entry_type: PlantCoordinateType)
	
PlantCoordinateType	 (data_class: ContributionImage)
  - index
  - coordinate
  - imageFile
  - description
  
Handler/Commands:  
  - PlantRegistrationCreateHandler
    - validates 
	  - plant projects belongs to authenticated TPO
	  - geometry matches the number of provided LocationCoordinates
	- creates
	  - 1 PlantContribution with generated location id
	  - n ContributionImages with coordinate id (coord_wJMJ5DWXfAkD1GqcZ2alpl5q) no image
	- associates 
	  - each ContributionImage with the PlantContribution
	  - the PlantContribution to the PlantProject
	  
  - PlantRegistrationUpdateHandler
    - validation similar to creation
	- properties that can be modified
	  - plantDate
	  - geometry (coordinates may only lie in a pre-defined distance)
	  - captureMode ???
	  - species???
  - PlantCoordinateUpdateHandler
    allows the upload/update of
    - image
	- description

**Comment by jmiridis** [comment]
Link to API definition
https://gist.github.com/jmiridis/f9025c5df6f5e0031ea9017602cc30c4
